[default]
address = "0.0.0.0"

[default.limits]
# only allow 128 KiB of data to be uploaded
"plain/text" = "128 KiB"

[default.pasty]
# the path to the database file
db_path = "berry-pasty.redb"

# the password required to add or delete, set to "" if not needed
access_password = "password"

# the length of the random ID for pastes
random_id_length = 8

# The text displayed on the index page,
# if index_link is specified, it will redirect to the link directly
index_text = "Welcome Berry Pastyï¼"
index_link = ""
